## Standard

AlignParameters:
  Enabled: false

AmbiguousOperator:
  Enabled: false

Encoding:
  Enabled: false

ClassLength:
  Enabled: false

MethodLength:
  Enabled: false

ModuleLength:
  Enabled: false

LineLength:
  Enabled: false

Documentation:
  Enabled: false

PerceivedComplexity:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

## Metrics

Metrics/AbcSize:
  Enabled: false

## Style

Style/FileName:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/WordArray:
  Enabled: false
