source 'https://rubygems.org'

gem 'berkshelf', '~> 3.2'
gem 'chef', '~> 11.18'
gem 'chefspec', '~> 4.2'
gem 'foodcritic', '~> 4.0'
gem 'kitchen-vagrant', '~> 0.15'
gem 'rake', '~> 10.4'
gem 'serverspec', '~> 2.7'
gem 'test-kitchen', '~> 1.3'
