source 'https://rubygems.org'

gem 'berkshelf', '~> 4.0'
gem 'chef', '~> 12.4'
gem 'chefspec', '~> 4.3'
gem 'foodcritic', '~> 5.0'
gem 'kitchen-vagrant', '~> 0.19'
gem 'knife-solo', '~> 0.5'
gem 'rubocop',  '~> 0.34'
gem 'serverspec', '~> 2.24'
gem 'test-kitchen', '~> 1.4'
